### ISSUE TITLE
Missing keys in state_dict for NoiseTransformer

### ISSUE THREAD

**Issue by specblades** [LucipherDev/ComfyUI-Golden-Noise#2]
Got it with example workflow

RuntimeError: Error(s) in loading state_dict for NoiseTransformer:
        Missing key(s) in state_dict: "swin.layers.0.blocks.0.attn.relative_position_index", "swin.layers.0.blocks.1.attn_mask", "swin.layers.0.blocks.1.attn.relative_position_index", "swin.layers.1.blocks.0.attn.relative_position_index", "swin.layers.1.blocks.1.attn_mask", "swin.layers.1.blocks.1.attn.relative_position_index", "swin.layers.2.blocks.0.attn.relative_position_index", "swin.layers.2.blocks.1.attn_mask", "swin.layers.2.blocks.1.attn.relative_position_index", "swin.layers.2.blocks.2.attn.relative_position_index", "swin.layers.2.blocks.3.attn_mask", "swin.layers.2.blocks.3.attn.relative_position_index", "swin.layers.2.blocks.4.attn.relative_position_index", "swin.layers.2.blocks.5.attn_mask", "swin.layers.2.blocks.5.attn.relative_position_index", "swin.layers.3.blocks.0.attn.relative_position_index", "swin.layers.3.blocks.1.attn.relative_position_index".

**Comment by LucipherDev** [comment]
Thank you for reporting this issue.

Please provide the settings you used [model_id, npnet_model, device] when this happened so I can try to replicate the results.

**Comment by specblades** [comment]
sdxl 1.0, sdxl.safetensors (from your link), both cuda/cpu,
no another changes in your workflow

**Comment by LucipherDev** [comment]
I just tried reproducing the error with the settings you gave me and some other combinations I thought might cause issues. Unfortunately, I wasn't able to reproduce the error you encountered.

However, It might be that you installed the node before I added support for Safetensors files. So please try updating the node.

**Comment by specblades** [comment]
It's weird. I cloned repo yesterday. Also i tried with vanilla pth models and got the same error.
I'll try to reinstall manually, not through manager
